# Generated by Django 4.1.3 on 2022-11-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pci', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Dados'},
        ),
        migrations.RemoveField(
            model_name='data',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='data',
            name='population',
        ),
        migrations.AddField(
            model_name='data',
            name='endereco',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='data',
            name='orgao',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='data',
            name='salario',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='uf',
            field=models.CharField(default='', max_length=2),
        ),
    ]
