# Generated by Django 4.1.3 on 2022-11-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pci', '0002_alter_data_options_remove_data_pais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='link',
            field=models.CharField(default='', max_length=400),
        ),
    ]
